const KEY_LOGS="esp32_logs",KEY_USERS="esp32_users";let logs=JSON.parse(localStorage.getItem(KEY_LOGS)||"[]"),users=JSON.parse(localStorage.getItem(KEY_USERS)||"[]");const $=id=>document.getElementById(id);
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.page).classList.add("active");renderAll()});
function save(){localStorage.setItem(KEY_LOGS,JSON.stringify(logs));localStorage.setItem(KEY_USERS,JSON.stringify(users))}
function renderAll(){renderLogs();renderUsers();renderRecent();$("today").textContent=logs.filter(x=>new Date(x.time).toDateString()===new Date().toDateString()).length;$("userCount").textContent=users.length}
function renderLogs(){let q=($("search")?.value||"").toLowerCase(),a=logs.filter(x=>(x.uid+x.name).toLowerCase().includes(q));$("logBody").innerHTML=a.length?a.map(x=>"<tr><td>"+new Date(x.time).toLocaleString("th-TH")+"</td><td>"+x.uid+"</td><td>"+x.name+"</td><td><span class='badge "+(x.granted?"grant":"deny")+"'>"+(x.granted?"อนุญาต":"ปฏิเสธ")+"</span></td><td>"+x.action+"</td></tr>").join(""):"<tr><td colspan='5'>ยังไม่มีข้อมูล</td></tr>"}
function renderRecent(){let a=logs.slice(0,5);$("recent").innerHTML=a.length?a.map(x=>"<div class='recentitem'><b>"+x.name+"</b> • "+x.uid+"<br><small>"+new Date(x.time).toLocaleString("th-TH")+"</small></div>").join(""):"ยังไม่มีการสแกน"}
function renderUsers(){$("userBody").innerHTML=users.length?users.map((u,i)=>"<tr><td>"+u.name+"</td><td>"+u.uid+"</td><td>"+u.role+"</td><td><button class='danger' onclick='removeUser("+i+")'>ลบ</button></td></tr>").join(""):"<tr><td colspan='4'>ยังไม่มีผู้ใช้</td></tr>"}
function addUser(){let name=prompt("ชื่อผู้ใช้:");if(!name)return;let uid=prompt("UID บัตร เช่น A3:B4:C5:D6:");if(!uid)return;users.push({name,uid:uid.toUpperCase(),role:"User"});save();renderAll()}
function removeUser(i){if(confirm("ลบผู้ใช้นี้?")){users.splice(i,1);save();renderAll()}}
function clearLogs(){if(confirm("ล้างประวัติทั้งหมด?")){logs=[];save();renderAll()}}
function saveSettings(){localStorage.setItem("esp_ip",$("espIp").value.trim());alert("บันทึกแล้ว")}
function testConnection(){let ip=$("espIp").value.trim();if(!ip){alert("ใส่ IP ของ ESP32 ก่อน");return}fetch("http://"+ip+"/api/status").then(r=>r.json()).then(()=>{setOnline(true);alert("เชื่อมต่อสำเร็จ")}).catch(()=>{setOnline(false);alert("เชื่อมต่อไม่ได้ หรือ ESP32 ยังไม่มี API")})}
function setOnline(v){$("conn").textContent=v?"● Online":"● Offline";$("conn").className="pill "+(v?"online":"offline");$("esp").textContent=v?"Online":"Offline";$("wifiStatus").textContent=v?"Connected":"Offline"}
$("espIp").value=localStorage.getItem("esp_ip")||"";renderAll();